registry:
  managers:
    datasets: lsst.daf.butler.registry.datasets.byDimensions.ByDimensionsDatasetRecordStorageManagerUUID
datastore:
  composites:
    default: true
    disassembled:
      calexp: false
  formatters:
    calexp:
      formatter: lsst.obs.base.formatters.fitsExposure.FitsExposureFormatter
      parameters:
        recipe: lossy16
